### ISSUE TITLE
[REQUEST] Frostmourne Sunwell Updates

### ISSUE THREAD

**Issue by GramGramZugZug** [Zidras/DBM-Warmane#101]
### Sunwell 1st boss Kalecgos (and Sathrovarr)

**Request**: Add a 5 minute (300s) enrage timer. ( was not in the original fight, but has been added on frostmourne)

**Request**: a pull reset is often used to get into position after pulling and resetting the boss. the boss respawns after 30 seconds whereupon the fight begins. Sadly this seems to bug out the dbm.
Is there a way to fix this?

_(log picture below)_  
19:38:46 – 19:43:45 = 4:59 = 5 minute enrage	(300 seconds)
 
### Sunwell 2nd boss, Brutallus

**Request**: Change enrage timer to 300s ( 5 minutes)

**Request**: if possible add a counter to the meteor slash mechanic emote to track the meteor slash debuff stacks on the tanks. (similar to the first TOC boss, Gormok the Impaler)

_(log picture below)_  
55:58-51:01 = 4:57 = 5 min enrage

### Sunwell	3rd boss, Felmyst

**Request**: Change enrage timer to 500s ( 8 minutes and 20 seconds)

**Request**: is it possible to put out a raid warning for the direction of the boss’s flight path?( tree, middle or fire wall)
 I'm guessing it's not possible however
 
_(NO log picture)_  
Sadly my logs broke on this encounter, but I have personally timed it twice to exactly 8 minutes and 20 seconds (500s) as opposed to 10 minutes
 
### Sunwell 4th boss, Eredar twins

**Request**: Change enrage timer 300s (5 minutes)

**Request**: Conflagration warning: is it possible to put a mark on the person the boss is casting it on, with a warning to move out of 8 yards? (mostly for melee, since ranged is already spread)
Encounter Start

_(log picture below)_    
22:41:23 - 22:46:34 = 5:11 = 5 minute enrage.
This one is a relative soft enrage because of the kiting possibility after the tanks get one-shot.

### Log Pictures
![Enrage logs](https://user-images.githubusercontent.com/97859911/149686138-fd471ea6-c62b-4914-922e-4b8e6080224c.jpg)

**Comment by Zidras** [comment]
Thank you for the descriptive ticket. I'll look into it when I get the chance. Idk the fights, so I'll be purely relying on what I read on the ticket and on the code

**Comment by Zidras** [comment]
> ### Sunwell 1st boss Kalecgos (and Sathrovarr)
> **Request**: Add a 5 minute (300s) enrage timer. ( was not in the original fight, but has been added on frostmourne)

OK.

> **Request**: a pull reset is often used to get into position after pulling and resetting the boss. the boss respawns after 30 seconds whereupon the fight begins. Sadly this seems to bug out the dbm. Is there a way to fix this?

Could not implement. DBM wipe code takes a few seconds to confirm the combat finished, to prevent false positives. Sadly, there's no ENCOUNTER events in wotlk to be accurate on this reading.
 
> ### Sunwell 2nd boss, Brutallus
> **Request**: Change enrage timer to 300s ( 5 minutes)

OK

> **Request**: if possible add a counter to the meteor slash mechanic emote to track the meteor slash debuff stacks on the tanks. (similar to the first TOC boss, Gormok the Impaler)

OK

> ### Sunwell 3rd boss, Felmyst
> **Request**: Change enrage timer to 500s ( 8 minutes and 20 seconds)

OK 

> **Request**: is it possible to put out a raid warning for the direction of the boss’s flight path?( tree, middle or fire wall) I'm guessing it's not possible however
There's no events that I know of that indicate boss position. Not possible.

> ### Sunwell 4th boss, Eredar twins
> **Request**: Change enrage timer 300s (5 minutes)

OK

> **Request**: Conflagration warning: is it possible to put a mark on the person the boss is casting it on, with a warning to move out of 8 yards? (mostly for melee, since ranged is already spread)

Already coded.
https://github.com/Zidras/DBM-Warmane/blob/main/DBM-Sunwell/EredarTwins.lua#L125-L137
