### ISSUE TITLE
[REQUEST]Boss Taunt 

### ISSUE THREAD

**Issue by Basaofficial** [Zidras/DBM-Warmane#102]
Is it possible to make DBM taunt feature that is possible to link in Raid Frames or Party or an addon to link who taunted Bosses etc 
Example 

DBM-Z : Diq has Taunted Boss with [Dark Command] 
DBM -Z Diq has Failed to taunt Boss with [Dark command]
and able to link it in chat

**Comment by Zidras** [comment]
This would fall outside the scope of DBM. Such tasks are better suited for addons, for example a quick weakaura to send chat messages
