### ISSUE TITLE
[REQUEST]auto mark Kinetic on BPC

### ISSUE THREAD

**Issue by Nispodzianka** [Zidras/DBM-Warmane#104]
is it possible for DBM to set the mark on Kinetic (BPC) ?
let's say:
The 1st kinetic is a square, the 2nd circle and the 3rd triangle - the 1st disappears and the 4th appears and gets the square

this would make it easier for people in the raid to keep an eye on which kinetic they are responsible for

**Comment by oli356** [comment]
Nice idea ..

**Comment by Zidras** [comment]
The idea is nice, the implementation however poses several challenges, one of which is not being able to rely on neither creature ID (because there's 3 orbs) nor GUID (because it's not visible in the log)

**Comment by Zidras** [comment]
Implemented a fixed descending order, 7 (cross) > 6 (square) > 5 (moon) > 7... (using higher indexes for hostiles to respect icon conventions)

**Comment by oli356** [comment]
Seems to work nicely, ty
