### ISSUE TITLE
[REQUEST] Pain and Suffering radar on LK P2 and P4

### ISSUE THREAD

**Issue by napnapnapnap** [Zidras/DBM-Warmane#106]
**Is your feature request related to a problem? Please describe.**
We had a change on LK fight on Lordaeron, on transition Pain and Suffering is doing way more damage than normal so it's important to spread better behind Raging Spirits.

**Describe the solution you'd like**
It would be nice to have a radar to see how DPS are spread behind the Raging Spirit to avoid having to heal too much.

**Comment by Zidras** [comment]
Hey Nap, I'll need more info regarding which range is best for the spread.
Also, the radar will not filter only dps, it will show all players in the said range.

**Comment by napnapnapnap** [comment]
I was picturing the same thing as on BPC/BQL, except it would work only in P2/4, and I'm sure it could be useful for every role.

**Comment by Zidras** [comment]
> I was picturing the same thing as on BPC/BQL, except it would work only in P2/4, and I'm sure it could be useful for every role.

But how many yards? 6 8 10 30?
Doing the radar on intermissions only is definitely possible

**Comment by napnapnapnap** [comment]
8 is sufficient. I can test it out next Wednesday.

**Comment by Zidras** [comment]
Any news?

**Comment by Zidras** [comment]
I have the implementation ready, just need a confirmation on the range:
<img width="589" alt="image" src="https://user-images.githubusercontent.com/10605951/152610351-df9fca54-9d05-4e9d-92f2-a9177c2c6cb9.png">
You can also test run this (if you wish, DM me on disc for the file)

**Comment by napnapnapnap** [comment]
Hey sorry for not responding, I had the opportunity to see it in action this week and it works great, I hope this will help people in mitigating this damage.
