### ISSUE TITLE
[BUG] Not Showing warning

### ISSUE THREAD

**Issue by Choooban** [Zidras/DBM-Warmane#107]
**Describe the bug**
DBM doesn't show warning for the ability ''Disrupting Shout'' from the creature ''Deathbound Ward'' in ICC.
If you go to options DBM - WOTLK - ICC - TRASH - ICECROWN TRASH.
First line in ''General Announces'' it says ''Show warning for Disrupting Shout'' and everything is enabled.

**DBM Version**
7.10

**To Reproduce**
1. Go to 'Icecrown Citadel raid'
2. Walk on hidden trap and spawn Deathbound Ward.
3. Wait for Deathbound Ward to cast Disrupting Shout.

**Expected behavior**
Clear warning that tells you to stop cast.

```

**Comment by Zidras** [comment]
Hi @Choooban , I will need a transcriptor log to diagnose the problem. https://github.com/Zidras/Transcriptor-WOTLK#how-to-use

**Comment by Zidras** [comment]
couldn't reproduce.
<img width="369" alt="image" src="https://user-images.githubusercontent.com/10605951/151892026-b7e5a448-2686-43cf-a5d5-55164cabe948.png">
Provide the requested transcriptor log and I'll reopen if there's an issue
