### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by napnapnapnap** [Zidras/DBM-Warmane#111]
**Describe the bug**
Bug after wipe on RS25 HC

**DBM Version**
`/dbm ver` to check your DBM version.
7.10 DBM-Warmane by Zidras (7010) 

**Error Log**

```
Message: Interface\AddOns\DBM-Core\DBM-Core.lua:9576: attempt to compare number with string
Time: 02/16/22 22:39:32
Count: 2
Stack: (tail call): ?
[C]: ?
Interface\AddOns\DBM-Core\DBM-Core.lua:9576: in function `Start'
...nterface\AddOns\DBM-ChamberOfAspects\Ruby\Halion.lua:268: in function `OnSync'
Interface\AddOns\DBM-Core\DBM-Core.lua:10643: in function `ReceiveSync'
Interface\AddOns\DBM-Core\DBM-Core.lua:3696: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:3691>
(tail call): ?
Interface\AddOns\DBM-Core\DBM-Core.lua:4592: in function `?'
Interface\AddOns\DBM-Core\DBM-Core.lua:760: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:747>

Locals: (*temporary) = "CHAT_MSG_ADDON"
(*temporary) = "DBMv4-Mod"
(*temporary) = "Halion	4390	Meteor	"
(*temporary) = "RAID"
(*temporary) = "Kuuftw"
(*temporary) = "CHAT_MSG_ADDON"
(*temporary) = "DBMv4-Mod"
(*temporary) = "Halion	4390	Meteor	"
(*temporary) = "RAID"
(*temporary) = "Kuuftw"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = <function> defined =[C]:-1

```

**Comment by Zidras** [comment]
How to repro?

**Comment by napnapnapnap** [comment]
We simply wiped on RS25HC, nothing specific happened.

**Comment by Zidras** [comment]
Nap, I can't reproduce this issue, not with just this information. The error just points me to a type mismatch of bar.cooldown that shouldn't be a string at all, so I'll need more information

**Comment by napnapnapnap** [comment]
Yes I understand this is too ambiguous, but I don't have more information. Next RS I'll activate the transcriptor in hopes to have something more.

**Comment by Zidras** [comment]
You can leave

**Comment by Zidras** [comment]
Info from another user helped me pinpoint the issue with this bug. Basically if any voice other than a Count Voice is selected in the mod timer voice dropdown, will lua error on 0:
![image](https://user-images.githubusercontent.com/10605951/166166849-71db8432-246b-488a-88f9-35dce1c5d038.png)
Until a fix is pushed, only use Count voice 1-3
