### ISSUE TITLE
[REQUEST] - loot method switch on/after boss fight

### ISSUE THREAD

**Issue by koni3c** [Zidras/DBM-Warmane#116]
Description:
I always use Master Looter on boss loot and group loot on thrash mobs. I think It would be help for many raid leaders to help with loot switch

Solution:
Option to enable/disable this feature of loot method switch
When enabled, a popup window will come on boss fight start (or even better on /dbm pull timer) in case that Master Loot is not set and it will ask for loot method switch to Master Loot (YES/NO).
After boss fight, similar popup will come and ask for Group Loot switch. (this may happen with some delay 1-2min after boss fight)

This can be configured/implemented in many ways, so just my suggestion is to help with loot method switch.

Thanks :)

**Comment by Zidras** [comment]
After consideration, this falls outside the scope of DBM.
