### ISSUE TITLE
Range radar [BUG]

### ISSUE THREAD

**Issue by Sheeri23** [Zidras/DBM-Warmane#120]
**Description**
When i try to use range radar it spams in chat:
<DBM> Radar is unavailable in this location: GetPlayerMapPosition("player") = 0, 0 
and it switches to text frame untill i change it manualy.

 7.10 DBM-Warmane by Zidras (7010) 

**To Reproduce**
Go to ICC and enable range radar (for sure it doesnt work on LK fight, didnt pay attention on rest)

**Expected behavior**
Rage radar should either work or switch back to range radar from text automatically whenever it's usable.

**Video**
https://youtu.be/A2c51vb94oo

**Comment by Zidras** [comment]
Download Trimitor map patch, or use the HD client. This is a blizzard bug, not dbm
