### ISSUE TITLE
[REQUEST] Lord Jaraxxus

### ISSUE THREAD

**Issue by msaramon** [Zidras/DBM-Warmane#125]
Hi.About the Lord jaraxxus Boss from TOGC raid.in Hard mode boss have a spelldebuff [Touch of Jaraxxus] following that [Curse of the Nether] effecting  on raid members.there is no option in this boss options addon.

**Comment by Zidras** [comment]
> Hi.About the Lord jaraxxus Boss from TOGC raid.in Hard mode boss have a spelldebuff [Touch of Jaraxxus] following that [Curse of the Nether] effecting on raid members.there is no option in this boss options addon.

Please attach a transcriptor log so that I can see the IDs and timings

**Comment by Zidras** [comment]
From all the logs I had, there was no entry for either of those spells. Closing due to incomplete report.
