### ISSUE TITLE
[BUG] Frostmourne - Gluth & Sapphiron enounter

### ISSUE THREAD

**Issue by zNuc** [Zidras/DBM-Warmane#127]
**Describe the bug**
Gluth - when its about to decimate, dbm announces "Decimate" 20 times and its like an ear rape.
Sapphiron - when sapphiron is about to die, i think on 20% hp dbm announces something like "WarnSaphLow"
**DBM Version**
7.11

**To Reproduce**
1. Go to 'Gluth'
2. Wait for Decimate
3. See that dbm announces Decimate 20 times in a row

**To Reproduce**
1. Go to 'Sapphiron'
2. Dps until 20%
3. See the bugged announcement

**Expected behavior**
Gluth - only 1 announcement
Sapphiron - fixed text for announcement

**Comment by Zidras** [comment]
@zNuc Thanks for your report. Saph has been fixed already.
Gluth I'll take a look. Do you have a transcriptor log?

**Comment by zNuc** [comment]
> @zNuc Thanks for your report. Saph has been fixed already. Gluth I'll take a look. Do you have a transcriptor log?

unfortunately i dont

**Comment by ForestJ316** [comment]
@Zidras Here is transcriptor log for Gluth with debug level 2, I started it before pipe run.
[Naxxramas_Gluth_Transcript.txt](https://github.com/Zidras/DBM-Warmane/files/8635441/Naxxramas_Gluth_Transcript.txt)

**Comment by Zidras** [comment]
Couldn't test locally. If after updating the addon it is still spamming the Decimate warning, reply to this message and I will reopen
