### ISSUE TITLE
When a ready check is performed, play sound through Master or Dialog audio channel and flash application icon.

### ISSUE THREAD

**Issue by Svannie** [Zidras/DBM-Warmane#136]
Hi,
"When a ready check is performed, play sound through Master or Dialog audio channel and flash application icon."
This feature is broken and does not produce any sound.

It used to work nicely few updates back. 

![image](https://user-images.githubusercontent.com/28999531/171109350-e5efa4fa-e7ff-46b0-9be7-cdbb09abcc82.png)

**Comment by broizter** [comment]
Seems to be fixed in 9.2.
