### ISSUE TITLE
[REQUEST] Designation of the name in the BG table.

### ISSUE THREAD

**Issue by moonxds** [Zidras/DBM-Warmane#137]
Can you pleasse change it? 

Before:
https://imgur.com/a/rNt2L7W

Now: :(
https://imgur.com/a/mdIW6dC

Thank you.

**Comment by Zidras** [comment]
How before are we talking about? what version
Also test with only dbm

**Comment by moonxds** [comment]
I do not know what version exactly, because after downloading your version I have to replace the DBM-PvP folder, because it is as I wrote.

**Comment by Zidras** [comment]
attach here that dbm-pvp folder

**Comment by moonxds** [comment]
[DBM-PvP.zip](https://github.com/Zidras/DBM-Warmane/files/8840408/DBM-PvP.zip)

**Comment by Zidras** [comment]
<img width="340" alt="image" src="https://user-images.githubusercontent.com/10605951/172063043-58ab5776-9b29-4774-945f-769aa507f8f2.png">

this works for you?

**Comment by Zidras** [comment]
your suggestion/blizzard is not suited for color. Not everyone has perfect eyesight and can perceive colors accurately:
<img width="307" alt="image" src="https://user-images.githubusercontent.com/10605951/172063311-009e7575-cfec-4def-89fd-1766ea413fa6.png">

**Comment by moonxds** [comment]
No, I mean my nickname is yellow. I can find it quickly in the table.

**Comment by moonxds** [comment]
> 

Yes, i mean this

**Comment by Zidras** [comment]
> your suggestion/blizzard is not suited for color. Not everyone has perfect eyesight and can perceive colors accurately: <img alt="image" width="307" src="https://user-images.githubusercontent.com/10605951/172063311-009e7575-cfec-4def-89fd-1766ea413fa6.png">

This I won't implement, for the reason I explained in the post. 

I will however push the > name < , which makes more sense from a UI/UX perspective

**Comment by moonxds** [comment]
OK, i understand you. Thank you, he reacted so quickly to my suggestion.

**Comment by moonxds** [comment]
Could you please share the yellow color version of the nickname you made for me?

**Comment by Zidras** [comment]
This will be fixed by this commit https://github.com/Zidras/DBM-Warmane/commit/ffde9f38f4488d41a5ffed508155dc452fb604ba

To see color instead, do this
```lua
if name and name ~= playerName then
```
<img width="576" alt="image" src="https://user-images.githubusercontent.com/10605951/172063976-c6905a45-a076-4ae5-9a92-5651221e8492.png">

**Comment by moonxds** [comment]
OK, thank you so much.
