### ISSUE TITLE
[BUG] Trash pack after boss killed triggers boss fight

### ISSUE THREAD

**Issue by broizter** [Zidras/DBM-Warmane#141]
**Describe the bug**
After killing a boss, the next trash pack you pull after that always triggers DBM as if the previous boss was pulled again (timers show up etc).
This is a new bug since 9.12.20-alpha. Let me know if there's something else you need to know.

**DBM Version**
9.12.20-alpha

**Comment by Zidras** [comment]
You're not the first to report it but I haven't yet been able to repro this issue

**Comment by Zidras** [comment]
@broizter, download/update transcriptor and generate a debuglevel 5 log please (you can attach it here or DM me the file on discord). 
I have a few suspicions but haven't been able to repro on test server.

**Comment by broizter** [comment]
Alright, I'll post a transcriptor log in a few days.

**Comment by Zidras** [comment]
Potential fix on https://github.com/Zidras/DBM-Warmane/commit/d9f2197bfe4eaa477f1732271000c58be1d83bf8
