### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by rainlife1** [Zidras/DBM-Warmane#142]
**no boss options or spells**
just deleted all my previous dbm files and went ahead and deleted all the account / character settings files aswell and when i installed the new version i didnt get the option for the bosses like in this video https://www.youtube.com/watch?v=QxjzHYXqkn4, in fact no options at all

**9.2.20**

**bruh :v**
https://www.youtube.com/watch?v=QxjzHYXqkn4A 

**Screenshot**
![image](https://user-images.githubusercontent.com/107188063/172835609-5934f034-6979-46cc-a678-3db9772ee394.png)

**Transcriptor**
If bug is related to a raid mechanic/timer, add a Transcriptor log (https://github.com/Zidras/Transcriptor-WOTLK#how-to-use).

**Additional context**
none

**Error Log**

```

```

**Comment by Zidras** [comment]
You probably have outdated elvui and addonskins. Update those, enable lua errors and paste Lua error here. Closing unless there's clear evidence of dbm bug
