### ISSUE TITLE
[BUG] Bar texture/font settings always reset

### ISSUE THREAD

**Issue by broizter** [Zidras/DBM-Warmane#144]
**Describe the bug**
The settings for bar texture and font gets cleared as soon as you relog or reload your UI. When you visit the settings page there's actually no value at all set.

This is how they look as soon as you relog or reload UI. https://i.imgur.com/SgC6fw5.png
This is what the settings page resets to every time. https://i.imgur.com/acb4vEd.png

**DBM Version**
[9.12.20-alpha](https://github.com/Zidras/DBM-Warmane/releases/tag/9.2.20_alpha)

**To Reproduce**
1. Change bar texture or font.
2. Reload UI
3. Visit settings page and the settings are gone

**Comment by Zidras** [comment]
If you're using fonts or texture from ElvUI without a SharedMedia that has them, it will do that. I'll close this unless you can repro with just DBM enabled

**Comment by broizter** [comment]
It should be noted that this was not an issue before 9.12.20-alpha
