### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jpujol880807** [Zidras/DBM-Warmane#145]
**Describe the bug**
Confict with elvui.

**DBM Version**
`/dbm ver` to check your DBM version.
Elvui 6.08
DBM 9.2.20

**To Reproduce**
1. Do a clean install with the  elvui and latest dbm
2. Activate the view lua error in wow
3. Open the dbm interface

**Expected behavior**
No error should be thrown in the elvui interface

**Video**
If applicable, add a video to help explain your problem.

**Transcriptor**
If bug is related to a raid mechanic/timer, add a Transcriptor log (https://github.com/Zidras/Transcriptor-WOTLK#how-to-use).

**Additional context**

**Error Log**

```
Message: ...terface\AddOns\ElvUI_AddOnSkins\Skins\Addons\dbm.lua:420: attempt to index global 'DBM_GUI_OptionsFrameBossModsList' (a nil value)
Time: 06/13/22 11:54:30
Count: 2
Stack: [C]: ?
...terface\AddOns\ElvUI_AddOnSkins\Skins\Addons\dbm.lua:420: in function <...terface\AddOns\ElvUI_AddOnSkins\Skins\Addons\dbm.lua:416>
(tail call): ?
[C]: ?
[C]: in function `Show'
Interface\AddOns\DBM-GUI\DBM-GUI.lua:293: in function `ShowHide'
Interface\AddOns\DBM-Core\DBM-Core.lua:1776: in function `LoadGUI'
Interface\AddOns\DBM-Core\modules\MinimapButton.lua:25: in function `OnClick'
...AddOns\DBM-Core\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:122: in function <...AddOns\DBM-Core\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:122>

Locals: 
```

**Comment by Zidras** [comment]
Update both elvui and addonskins to their latest Master versions (not release)

**Comment by jpujol880807** [comment]
Thanks problem solved
