### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by rainlife1** [Zidras/DBM-Warmane#147]
**my dbm fails to load sometimes, and fails to load boss options**
My Dbm doesnt load when i /dbm often and when it does it doesnt display the options for specific bosses, i posted before without lua code, and was told that its a problem with my lvui etc but ive double checked them im using elv ui 6.08 and weak auras 3.2.3, and my addon list doesnt show any outdated add on.
**DBM 9.2.20 alpha**
`/dbm ver` to check your DBM version.

**To Reproduce**

**Expected behavior**

**Video**
If applicable, add a video to help explain your problem.

**Transcriptor**
If bug is related to a raid mechanic/timer, add a Transcriptor log (https://github.com/Zidras/Transcriptor-WOTLK#how-to-use).

**Additional context**

**Error Log**

```Message: Interface\AddOns\DBM-GUI\modules\PanelPrototype.lua:579: attempt to call method 'HandleCollapseTexture' (a nil value)
Time: 06/18/22 13:53:49
Count: 3
Stack: [C]: in function `HandleCollapseTexture'
Interface\AddOns\DBM-GUI\modules\PanelPrototype.lua:579: in function `CreateAbility'
Interface\AddOns\DBM-GUI\DBM-GUI.lua:444: in function `CreateBossModPanel'
Interface\AddOns\DBM-GUI\DBM-GUI.lua:866: in function `UpdateModList'
Interface\AddOns\DBM-Core\DBM-Core.lua:3117: in function `LoadMod'
Interface\AddOns\DBM-GUI\DBM-GUI.lua:831: in function <Interface\AddOns\DBM-GUI\DBM-GUI.lua:830>

Locals: 

Message: Interface\AddOns\DBM-GUI\modules\PanelPrototype.lua:579: attempt to call method 'HandleCollapseTexture' (a nil value)
Time: 06/18/22 13:54:12
Count: 1
Stack: [C]: in function `HandleCollapseTexture'
Interface\AddOns\DBM-GUI\modules\PanelPrototype.lua:579: in function `CreateAbility'
Interface\AddOns\DBM-GUI\DBM-GUI.lua:444: in function `CreateBossModPanel'
Interface\AddOns\DBM-GUI\DBM-GUI.lua:866: in function `UpdateModList'
Interface\AddOns\DBM-GUI\DBM-GUI.lua:292: in function `ShowHide'
Interface\AddOns\DBM-Core\DBM-Core.lua:1776: in function `LoadGUI'
Interface\AddOns\DBM-Core\modules\Commands.lua:489: in function `?'
Interface\FrameXML\ChatFrame.lua:4049: in function `ChatEdit_ParseText'
Interface\FrameXML\ChatFrame.lua:3660: in function `ChatEdit_SendText'
Interface\FrameXML\ChatFrame.lua:3698: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals: ```

**Comment by Stekolnyu** [comment]
Just update elvui and weakauras

**Comment by rainlife1** [comment]
ive been downloading the supposed latest version of elv ui, if u dont mind can u link me just to be sure cz ive downloaded it 3 times now, and im pretty sure its the cause of the problem, cz dbm works fine when i turn it offre

**Comment by rainlife1** [comment]
> Just update elvui and weakauras

help me, how ?

**Comment by Zidras** [comment]
https://i.imgur.com/5P12bqth.jpg

**Comment by rainlife1** [comment]
> https://i.imgur.com/5P12bqth.jpg

Zoinks! You've taken a wrong turn.
Let's split up, gang. If you're looking for an image, it's probably been deleted or may not have existed at all.
