### ISSUE TITLE
[BUG] Bars Overlapping when set to Lowest at top

### ISSUE THREAD

**Issue by S4MZ1N** [Zidras/DBM-Warmane#148]
**Describe the bug**
When I sort the remaining time of a bar as Lowest at top, the bars start overlapping each other.

**DBM Version**
DBM Version 9.2.20

**To Reproduce**
1. Go to 'DBM options tab'
2. Click on 'Bar Appearance on the section "Timers" '
3. Scroll down to 'Small bar options'
4. Click on 'Sort by remaining time'
5. Select the option 'Lowest at top'
6. Click on Start test bars.

**Expected behavior**
When I set this configuration the bars must not overlap.

**Comment by Zidras** [comment]
https://user-images.githubusercontent.com/10605951/174499505-32e92401-049a-48f7-a89c-9aef8398c7a5.mp4

can't repro.
