### ISSUE TITLE
Type mismatch on format()

### ISSUE THREAD

**Issue by Intervence** [Zidras/DBM-Warmane#153]
https://github.com/Zidras/DBM-Warmane/blob/cac9762b23ab4dcac22affb2bae8f06e18d9d8ee/DBM-Core/DBM-Core.lua#L3562
showRealDate(version) returns string instead of number which throws an error upon every update reminder. 
Probably needs to be wrapped in tonumber() or defined as string in format directly

**Comment by Zidras** [comment]
Thanks @Intervence for the input
