### ISSUE TITLE
DBM not active in serpentshrine caverns timewalking 

### ISSUE THREAD

**Issue by pstefanuca** [Zidras/DBM-Warmane#154]
**Describe the bug**
I cannot see DBM timers in SSC timewalking, on any boss.

**DBM Version**
latest

**To Reproduce**
1. Go to SSC
2. See error

**Expected behavior**
We should be able to see the timers since the timers are scripted.

**Comment by Zidras** [comment]
I'll require a transcriptor log

**Comment by Nessy27** [comment]
It looks like it is a MapID issue? DBM is looking for 781 when it should be 467. In DBM-Serpentshrine.toc, change the line to `## X-DBM-Mod-MapID: 467`

**Comment by Zidras** [comment]
> It looks like it is a MapID issue? DBM is looking for 781 when it should be 467. In DBM-Serpentshrine.toc, change the line to `## X-DBM-Mod-MapID: 467`

The log will provide the map ID and zone name.
781 is in line with the updated map patch.

**Comment by pstefanuca** [comment]
@Zidras I sent the log on discord, can t attach lua file here. But as a minimum, i could see in the log that SSC is indeed 467.

**Comment by Zidras** [comment]
Thing is, 467 is not unique due to missing maps.
```
Changed Channel: [3. LocalDefense - Serpentshrine Cavern]
Raid Difficulty set to 25 Player.
Dump: value=GetCurrentMapAreaID()
[1]=467
Dump: value=GetMapInfo()
[1]="Expansion01",
[2]=1883,
[3]=1920
Dump: value=GetRealZoneText()
[1]="Serpentshrine Cavern"
Dump: value=GetInstanceInfo()
[1]="Coilfang: Serpentshrine Cavern",
[2]="raid",
[3]=1,
[4]="25 Player",
[5]=25,
[6]=0,
[7]=false
Dump: value=DungeonUsesTerrainMap()
empty result
Level: 0 of 0

Changed Channel: [1. General - The Steamvault]
Dump: value=GetCurrentMapAreaID()
[1]=467
Dump: value=GetMapInfo()
[1]="Expansion01",
[2]=1883,
[3]=1920
Dump: value=GetRealZoneText()
[1]="The Steamvault"
Dump: value=GetInstanceInfo()
[1]="Coilfang: The Steamvault",
[2]="party",
[3]=1,
[4]="5 Player",
[5]=5,
[6]=0,
[7]=false
Dump: value=DungeonUsesTerrainMap()
empty result
Level: 0 of 0

Changed Channel: [1. General - The Slave Pens]
Dump: value=GetCurrentMapAreaID()
[1]=467
Dump: value=GetMapInfo()
[1]="Expansion01",
[2]=1883,
[3]=1920
Dump: value=GetRealZoneText()
[1]="The Slave Pens"
Dump: value=GetInstanceInfo()
[1]="Coilfang: The Slave Pens",
[2]="party",
[3]=1,
[4]="5 Player",
[5]=5,
[6]=0,
[7]=false
Dump: value=DungeonUsesTerrainMap()
empty result
Level: 0 of 0
```

I will push english loadzone, but I can guarantee more old instances will only have mapID because coding all locales names for text loadzone is too much of a hassle when there are better alternatives with a proper map patch:
https://discordapp.com/channels/598993375479463946/859859822149107732/899709926836961350
