### ISSUE TITLE
DBM Mimiron Bug

### ISSUE THREAD

**Issue by Narovoid** [Zidras/DBM-Warmane#165]
**Describe the bug**
In Mimiron 10 and 25man. I am not receiving any alerts for most mechanics in the fight. Only alerts I receive are barrage in P2, who picks up the magnetic core during P2.5 to bring the head down for melee to do damage. 
Currently there is no alerts for important mechanics like shock blast and plasma blast or any other mechanics.

**DBM Version**
DBM 9.2.26 alpha 

**To Reproduce**

**Expected behavior**
There is supposed to be alerts for every mechanic listed in DBM boss options but only 2 are working.

**Video**
N/A

**Transcriptor**

**Additional context**

**Error Log**

```

```

**Comment by Zidras** [comment]
Attach transcriptor log as instructed in the template
