### ISSUE TITLE
[BUG] different results for frost beacon targets' order than the rest of the raid

### ISSUE THREAD

**Issue by MRCORYA** [Zidras/DBM-Warmane#171]
### Are you using the latest DBM version in a Warmane 3.3.5a realm (Icecrown, Lordaeron or Frostmourne)?

- [X] Yes

### DBM version

DBM 9.2.26 alpha (2023/01/28 18:44:47)

### Current Behavior

During air phase for sindragosa's fight 25 nm, I have different results for beacon target order than the rest of the raid. 

### Expected Behavior

Frost beacon target order is unified and consistent with the rest of the raid members 

### Steps To Reproduce

Default settings for sindragosa

### Transcriptor log

NA

### Error log

```lua
NA
```

**Comment by Zidras** [comment]
Do you have video or transcriptor? I need a much better description of the problem
- how does it happen? 
- It happens every time?
- what order is being used on each round of beacons, raid and yours ?

**Comment by MRCORYA** [comment]
i installed this version of dbm just recently , and it's my first sindragosa fight with it , before it i was using the classical version that isn't updated for warmane , the order was totally random , sometimes i get the same results as the raid , and sometimes middle target is the same while the other two are reversed and sometimes it's all mingled and not the same at all , we did the fight around 8 times and it was the same problem , i will try to provide transcriptor and screenshots for my screen and let someone else record the entire fight from their prospective and ask if some other members where having the same issue or not, but we can't raid until next sunday probably if we were able to reach sindragosa

**Comment by Zidras** [comment]
Their transcriptor will also be needed to validate combat log order

**Comment by Zidras** [comment]
I have not changed anything regarding beacon order, nor have I ever received such a report.
DBM also has no say in the order, it follows what the client gives in terms of CLEU:SPELL_AURA_APPLIED order - first come, first serve. 
I will keep the issue open for a bit, but unless there is clear proof in transcriptor from same fight and different people, I'm afraid there's nothing I can do and will close the ticket

**Comment by Zidras** [comment]
No evidence provided
