### ISSUE TITLE
[REQUEST] Halion - Twilight Cutter

### ISSUE THREAD

**Issue by TheRealZuggy** [Zidras/DBM-Warmane#172]
### Is your feature request related to a problem? Please describe.

Halion cutters have two separate timers, one for cooldown and one for cast time. Sometimes if I'm not paying attention I'm not sure which timer is currently active and I'm not sure if it's 3 seconds until cast start or 3 seconds until cast end.

### Desired solution

An option to have a new timer that lasts 20 seconds and combines both cooldown (15s) and cast timers (5s) into one timer. This timer would basically show "time until next cutter starts".

### Describe alternatives you've considered

I've considered messing with the code by myself and extending the 15s timer to 20 but decided to make this request first.

**Comment by Zidras** [comment]
@TheRealZuggy try this implementation (untested)

**Comment by TheRealZuggy** [comment]
I did a normal RS 10 on warmane icecrown with these settings.

Twilight Cutter
Show warning when Twilight Cutter is being cast	- ON
Show special announce for Twilight Cutter		- ON
Show timer for Twilight Cutter cast (5s)			- OFF
Show timer for Twilight Cutter duration (10s)	- ON
Show timer for next Twilight Cutter (15s)		- OFF
Show timer until Twilight Cutter spawn			- ON

When phase 2 starts I get a twilight cutter spawn timer and it works perfectly but after the 1st cutter other timers don't show up until the cast starts. At that point "Twilight Cutter spawn" bar shows up with few seconds on it before cutter starts.

On 2nd try I turned on all the timers and the results were exactly the same.

Before doing the RS 10 I did rs 25 normal with the settings I listed above and I believe results were the same but I wasn't paying that much attention.

I also did another RS 25 normal with regular settings (first 5 options ON and the last one - the new timer OFF) and in it the timers were called "Next Twilight Cutter" for the 15 second one and "Twilight Cutter" for the 5 second cast timer.

So to sum up when the new option is enabled it works perfectly for only the first cutter and the text on bar says "Twilight Cutter spawn", for all cutters after the 1st one timer shows up after casts starts and text still says "Twilight Cutter spawn". 

It makes no difference whether the other timers (15s and 5s) are on or off it still behaves the same.

When new timer is off the and old ones are on addon behaves normally just like it used to before so after twilight cutter ends 15s timer shows up with text "Next Twilight Cutter" followed by a 5s timer called "Twilight Cutter" for the cast time.

Images:
	Images with new feature being used:
		"Twilight Cutter spawn" missing right after cutter ends: https://i.imgur.com/pW3lBCG.png
		"Twilight Cutter spawn" showing up late: https://i.imgur.com/NJgnOHb.png

	Images with new feature disabled:
		"Next Twilight Cutter" (15s) timer right after cutters: https://i.imgur.com/vrdKNGM.png
		"Twilight Cutter" (5s) timer for the cast:https://i.imgur.com/pFFVVVj.png

**Comment by Zidras** [comment]
> I did a normal RS 10 on warmane icecrown with these settings.
> 
> Twilight Cutter Show warning when Twilight Cutter is being cast - ON Show special announce for Twilight Cutter - ON Show timer for Twilight Cutter cast (5s) - OFF Show timer for Twilight Cutter duration (10s) - ON Show timer for next Twilight Cutter (15s) - OFF Show timer until Twilight Cutter spawn - ON
> 
> When phase 2 starts I get a twilight cutter spawn timer and it works perfectly but after the 1st cutter other timers don't show up until the cast starts. At that point "Twilight Cutter spawn" bar shows up with few seconds on it before cutter starts.
> 
> On 2nd try I turned on all the timers and the results were exactly the same.
> 
> Before doing the RS 10 I did rs 25 normal with the settings I listed above and I believe results were the same but I wasn't paying that much attention.
> 
> I also did another RS 25 normal with regular settings - NOT using the new feature (first 5 options ON and the last one - the new timer OFF) and in it everything worked fine and the timers were called "Next Twilight Cutter" for the 15 second one and "Twilight Cutter" for the 5 second cast timer.
> 
> So to sum up when the new option is enabled it works perfectly for only the first cutter and the text on bar says "Twilight Cutter spawn", for all cutters after the 1st one timer shows up after cast starts and text still says "Twilight Cutter spawn".
> 
> It makes no difference whether the other timers (15s and 5s) are on or off it still behaves the same.
> 
> When new timer is off the and old ones are on addon behaves normally just like it used to before so after twilight cutter ends 15s timer shows up with text "Next Twilight Cutter" followed by a 5s timer called "Twilight Cutter" for the cast time.
> 
> Images: Images with new feature being used: "Twilight Cutter spawn" missing right after cutter ends: https://i.imgur.com/pW3lBCG.png "Twilight Cutter spawn" showing up late: https://i.imgur.com/NJgnOHb.png
> 
> Images with new feature disabled: "Next Twilight Cutter" (15s) timer right after cutters: https://i.imgur.com/vrdKNGM.png "Twilight Cutter" (5s) timer for the cast: https://i.imgur.com/pFFVVVj.png

Updated PR. Should be good now

**Comment by Zidras** [comment]
I'm not super happy with the locale text. More ideas are welcome.
![image](https://user-images.githubusercontent.com/10605951/224506173-dfdb8afd-e034-407f-b3a7-c8a0ab683d2e.png)

![image](https://user-images.githubusercontent.com/10605951/224506155-a8998a79-b3a5-45ae-93ac-18d6a661cc01.png)

**Comment by TheRealZuggy** [comment]
Looks like it will work fine now, thanks.
For the locale text I'm thinking about what would describe it clearly so it's easy to understand. 

Show timer until next Twilight Cutter with cast included (20s) (disables Next and Cast timers) - this is what I'd go with.
