### ISSUE TITLE
[BUG] Weird message report

### ISSUE THREAD

**Issue by ProfessorMinius** [Zidras/DBM-Warmane#175]
### Are you using the latest DBM version in a Warmane 3.3.5a realm (Icecrown, Lordaeron or Frostmourne)?

- [X] Yes

### DBM version

DBM 9.2.26 alpha (2023/02/12 11:45:59)

### Current Behavior

Getting this weird report in my chat box and it's spamming me constantly.
![image](https://user-images.githubusercontent.com/25408719/225070810-97de4b3a-6704-478a-8c8e-fae191e9fb4f.png)

### Expected Behavior

I don't exactly know what to expect since it's just throwing this error

### Steps To Reproduce

1. Simply showing up in my chat box, it started when I installed the addon

### Transcriptor log

BA

**Comment by Zidras** [comment]
**Q**: Links to update DBM / After installing 9.2.20+, I have errors?
**A**: Here are direct links of Github for the latest versions of each relevant repository:
- DBM (https://github.com/Zidras/DBM-Warmane/archive/refs/heads/main.zip)
- ElvUI (https://github.com/ElvUI-WotLK/ElvUI/archive/refs/heads/master.zip),
- AddonSkins (https://github.com/ElvUI-WotLK/ElvUI_AddOnSkins/archive/refs/heads/master.zip) 
- WA (https://github.com/Bunny67/WeakAuras-WotLK/archive/refs/heads/master.zip) 
*These links will always be up-to-date, but on each commit you will have to re-download.*

If you don't want the hassle of managing updates, consider using the Github Addon Updater tool (essentially a 1-click updater for all your GH addons). I strongly recommend this tool if you're overwhelmed with updates: https://discord.com/channels/598993375479463946/600354296084561920/920034390522859590
