### ISSUE TITLE
[BUG] Lady Deathwhisper Mind Control Crashes

### ISSUE THREAD

**Issue by Geeksterer** [Zidras/DBM-Warmane#177]
### Are you using the latest DBM version in a Warmane 3.3.5a realm (Icecrown, Lordaeron or Frostmourne)?

- [X] Yes

### DBM version

DBM 9.2.26 alpha (2023/02/12 11:45:59)

### Current Behavior

Every time I get mind controlled on Lady Deathwhisper I crash. My weapons are in my bag when I log back in.

### Expected Behavior

I expected to be mind controlled and then be released without a crash when the time was up.

### Steps To Reproduce

1. Join icc raid
2. get mind controlled by Lady Deathwhisper

### Transcriptor log

NA

**Comment by Zidras** [comment]
This is not an indication of DBM being at fault here. If you can reproduce the issue with ONLY DBM enabled, I will take a closer look, but be aware that you are an isolated case and no other people have reported such crashes.
