### ISSUE TITLE
[REQUEST] Raid lead / assist settings (target marking)

### ISSUE THREAD

**Issue by Babette-Lordearon** [Zidras/DBM-Warmane#178]
### Is your feature request related to a problem? Please describe.

I've ran into some issues with assist in raid overriding icons, people having outdated dbm's and messing up mechanics, etc. I've heard and seen this in several raids and heard several raid leaders complain about this, so I thought I'd post a message here with some possible adjustments that could solve this issue.

(One of the) cause(s): It's quite handy for a tank to have assist so they can mark targets, but their dbm settings need to be the same as the RL, or you'll get 100 icon marks going out in a second and everybody is overwriting one another, which can cause problems if a tank is marked. For example the one kiting slime on Rotface.

### Desired solution

Is there a way to create a master/slave to have the assist copy the settings of the raid leader, just like a master/slave setup with HardDrives?
RL clicks a button, you get a popup to confirm, settings are copied.

Or without the confirm, but as a notification telling you it has changed. And a restore to default option after the raid, or upon restart if previous login had it changed(?)

### Anything else?

When RL has "mark targets with ability XYZ" turned off, but an assist has it turned on, it will be marked. Another option would be to restrict the marking to only the RL by default.
But then you'll run into people using 1 year old outdated DBM versions, so a force update function would also be really lovely!

**Comment by Zidras** [comment]
Right of the bat, I can say this: even if I implemeted this in DBM, it wouldn't make any difference by the same reason you describe - other people would also need to have the latest version...

**Comment by morgenstern09** [comment]
Just want to say thank you for your work!

**Comment by Zidras** [comment]
Retail implemented this https://github.com/Zidras/DBM-Warmane/commit/e537fc0d0a6522f35292097bad222a786d871dae
