### ISSUE TITLE
[REQUEST] QOL Organization & Settings

### ISSUE THREAD

**Issue by Babette-Lordearon** [Zidras/DBM-Warmane#180]
### Is your feature request related to a problem? Please describe.

Doing settings in DBM requires 100s of clicks to unfold folders and go over settings.

### Desired solution

Please add a button to collapse / unfold all buttons.
Things are now neatly organized per ability, but going over all settings of all bosses requires 100s of clicks. :rofl:

Maybe a button to "disable all" would also be nice to have for all target markings and such, and you can just enable the few ones that you DO want to have.

### Describe alternatives you've considered

Another option would be to create some profiles beforehand. Like on LK there is no need for a hunter to see the timer for soul reaper, but it is quite useful to see for the tank / healer. But then also useful for someone who has CDs to offer, such as any paladin (HoS). (I know profiles are able to be made already, but there are no premades).

**Comment by Zidras** [comment]
Such button already exists in core & gui
