### ISSUE TITLE
[REQUEST] LDW Spirits

### ISSUE THREAD

**Issue by IamMartinPeek** [Zidras/DBM-Warmane#185]
### Is your feature request related to a problem? Please describe.

Hey Guys,
is there a new idea how we can calculate the target of the spirits on lady death whisper ? I am currently looking deeper into it and just wanted to get some input from you, if there is anything upcomming?

### Desired solution

DBM announcing who got targeted by the spirits!

**Comment by Zidras** [comment]
Not possible on warmane, no threat table
