### ISSUE TITLE
[BUG] Client crash when during pull timer countdown

### ISSUE THREAD

**Issue by endershan** [Zidras/DBM-Warmane#192]
### Are you using the latest DBM version in a Warmane 3.3.5a realm (Icecrown, Lordaeron or Frostmourne)?

- [X] Yes

### DBM version

10.1.7 alpha (2023/06/14 00:01:56) (also true with release 10.1.6)

### Current Behavior

When RL started pull timer, at some point during the 10 seconds (maybe 15 on some bosses) countdown, the client crashes. All movement stops, after 1-2 seconds the screen turned grey, the mouse cursor turned into little circle, then windows decided the game client "not responding". User have to close it and relog into game.

Server: Lordaeron.

Boss: could happen to most RS and ICC bosses. It's more seen at Halion and PP, but this could also be due to more wipes and re-tries at these heroic bosses. I have also seen it at Festergut / Rotface. My crashes are all in 25man, since I haven't played 10 man recently. 

This could happen with different RLs, examples of RLs' names sending pull: Xiaoming, Youzoki.

The font I used (Chinese) is attached to this issue.
[ARHei.zip](https://github.com/Zidras/DBM-Warmane/files/13199750/ARHei.zip)

My Addons installed:
!BugGrabber
!ClassColors
ACP
ActionBarSaver
Alts
AtlasLoot
Auctionator
BonusScanner
BugSack
CL_Fix
ColorPickerAdvanced
DrDamage
ElvUI (WotLK)
ElvUI_MerfinUI_1440p
ErrorFilter
GatherMate
GearScore
Guild2Guild
HalionHelper
idQuestAutomation
KeyBindingsProfiler
LibGroupTalents-1.0
LibTalentQuery-1.0
MoveAnything
MTarget
MySlot
PallyPower
Postal
QDKP_V2
RaidAlerter
RaidBrowser
RaidRoll
SharedMedia
Skada
SnowfallKeyPress
SushiSort
Talented
WeakAuras
xCT+
YssBossLoot

Note: friend not using ElvUI has also seen this issue.

### Expected Behavior

Client doesn't crash.

### Steps To Reproduce

RL sending a pull timer could trigger this (not always).

### Transcriptor log

NA

### Anything else?

Client: mostly normal client, we haven't tried HD client. (Which is not common due to language localization issues).

**Comment by liponn** [comment]
I have the same question. i used the latest version.
In the picture,we can saw crashed(pull timer at 5 sec).
as usual.I aways relogin the game after every 1-2 bosses to prevent it from happening.
![image](https://github.com/Zidras/DBM-Warmane/assets/9856659/a951e9f9-b1fa-4cf2-8ccc-59c86e541dd0)

**Comment by Zidras** [comment]
@endershan @liponn, please share the `/dbm ver` of the raid you experienced the error and who sent the pull timer

**Comment by liponn** [comment]
@Zidras ,Sorry,I don't have much raid time.But I will actively test

**Comment by endershan** [comment]
> @Zidras Hi, this issue occurred again today at PP (25HC). Here is the `/dbm ver` of my raid, where Yss is the RL sent the pull timer ![95c91c7c7fa6fc01e8cc311d193f667](https://user-images.githubusercontent.com/68373127/283165058-3a69cdb0-3eae-43de-a65e-f63f825b22d7.png)

Some info to add: most raiders are playing in zhCN client, and after changing fonts I can sense less crashes (but it still happens). 
The two fonts I used:
[fonts.zip](https://github.com/Zidras/DBM-Warmane/files/13445858/fonts.zip)

**Comment by anzz1** [comment]
That access violation looks like the usual out-of-memory crash present on 3.3.5 clients.

The enUS client is stable when the large address aware flag is applied which increase the maximum available RAM to 4GB.
You can use [WowPatcher335](https://github.com/anzz1/WowPatcher335) to patch the enUS wow.exe to enable large address aware ( [x] "4GB RAM" )

I believe it is possible to use the 3.3.5.12340 (3.3.5a) enUS client, but with chinese fonts and localization MPQs. I have heard that the localized clients like ruRU and zhCN are more prone to crashing, so I suggest using the enUS client instead. If used with chinese font and localization, it should be same experience as with zhCN client but be more stable.

**Comment by Zidras** [comment]
@endershan try to disable CLEU auto clearing and check if it resolves the problem: 
![image](https://github.com/Zidras/DBM-Warmane/assets/10605951/2713ba52-1446-4ee7-bb81-0872639acf4c)

**Comment by endershan** [comment]
Thank you! I will test it tonight.

 

发件人: ***@***.*** ***@***.***> 代表 Zidras
发送时间: 2024年2月21日 9:00
收件人: Zidras/DBM-Warmane ***@***.***>
抄送: endershan ***@***.***>; Mention ***@***.***>
主题: Re: [Zidras/DBM-Warmane] [BUG] Client crash when during pull timer countdown (Issue #192)

 

@endershan <https://github.com/endershan>  try to disable CLEU auto clearing and check if it resolves the problem:
image.png (view on web) <https://github.com/Zidras/DBM-Warmane/assets/10605951/2713ba52-1446-4ee7-bb81-0872639acf4c>
