### ISSUE TITLE
[BUG] Addon clcret is always visible

### ISSUE THREAD

**Issue by Xezess** [Zidras/DBM-Warmane#196]
### Are you using the latest DBM version in a Warmane 3.3.5a realm (Icecrown, Lordaeron or Frostmourne)?

- [X] Yes

### DBM version

DBM 10.1.11alpha (2024/01/03 18:47:19)

### Current Behavior

Addon  clcret is always visible even  though it should be only when you get in combat or have a valid target.

### Expected Behavior

To be hidden/invisible until you have a target.

### Steps To Reproduce

NA

### Transcriptor log

NA

### Anything else?

![WoWScrnShot_011](https://github.com/Zidras/DBM-Warmane/assets/157238411/cca1f134-bcb4-4b25-8a37-04a9b11788eb)
https://youtu.be/PT8ErsCc05Y
[CLCRet-v.1.3.03.025.zip](https://github.com/Zidras/DBM-Warmane/files/13998845/CLCRet-v.1.3.03.025.zip)

**Comment by Zidras** [comment]
Cannot repro.

https://github.com/Zidras/DBM-Warmane/assets/10605951/621096cc-aed9-41f4-acbe-0f710fc18b2f

**Comment by Zidras** [comment]
Also, I may add that this addon throws Lua error when opening config...
