### ISSUE TITLE
[BUG] Kael'thas Sunstrider and Mage Flamestrike

### ISSUE THREAD

**Issue by Noob1e** [Zidras/DBM-Warmane#207]
### Are you using the latest DBM version in a Warmane 3.3.5a realm (Icecrown, Lordaeron or Frostmourne)?

- [X] Yes

### DBM version

DBM 10.1.12 alpha (2024/02/51 09:07:11)

### Current Behavior

If you use Flamestrike as a Mage while fighting Kael'thas Sunstrider in Tempest Keep, you will receive the same warning message as when Kael uses Flamestrike.

### Expected Behavior

You should only receive this warning if Kael is using Flamestrike.

### Steps To Reproduce

1. Go to Tempest Keep - The Eye as a Mage
2. Reach to Kael'thas Sunstrider
3. Get into combat (fight doesn't have to be started - getting into combat is enough)
4. Cast Flamestrike

### Transcriptor log

NA

### Anything else?

I'm not sure but it may require to be level 80.

**Comment by Zidras** [comment]
@Noob1e I could not repro this. Do you have a log?

**Comment by Noob1e** [comment]
Sorry, I don't have log but I'll try to get one this week. And my client language is English.

**Comment by Zidras** [comment]
> Sorry, I don't have log but I'll try to get one this week. And my client language is English.

@Noob1e, any news?

**Comment by Zidras** [comment]
@Noob1e , will you be arranging a log for your issue? Otherwise I will have to close this for lack of repro

**Comment by Noob1e** [comment]
I've tried it a few times in the past weeks. The last time it happened was 2 weeks ago but I couldn't log in then. I tried again this week but did not encounter the same problem. So I'm closing this issue.

**Comment by Zidras** [comment]
OK thanks for trying. If you rerun it, log it for me.
The mod definitely needs work, but I'm not investing time in it unless necessary
