### ISSUE TITLE
[BUG] Battleground health frame shows wrong values

### ISSUE THREAD

**Issue by emv33** [Zidras/DBM-Warmane#212]
### Are you using the latest DBM version in a Warmane 3.3.5a realm (Icecrown, Lordaeron or Frostmourne)?

- [X] Yes

### DBM version

10.1.12 2024/06/23 23:11:48

### Current Behavior

The health frame that opens in battlegrounds like sota or ioc never shows the correct values. For instance a door that is being demolished shows 100%, and then if it breaks maybe you'll get to 0%, or maybe not.

Boss health is erratic,  too. It would alternate between 100.0% (not sure why doors have no decimals whilst bosses do) and something like -1.$%, then after a wipe it wouldn't reset to 100.0%

### Expected Behavior

.

### Steps To Reproduce

.

### Transcriptor log

.

**Comment by Zidras** [comment]
@emv33 , gate health is unfortunately dependent on **vehicle's** DBM, not your own. The player only receives comms within battleground if the vehicle player is running my DBM to properly track gate damage, since the event only shows for vehicle owner.

As for boss health, can you please send me a Transcriptor Log? I can't debug this without that information. Thank you

**Comment by emv33** [comment]
Can't you get gate health from combat log?

**Comment by emv33** [comment]
More comments:

1) Gate list is unordered. Should be ordered somehow.

2) Joined AV and for some reason the list comes up as empty. Should not show the frame at all if there's nothing to show I think?

![image](https://github.com/user-attachments/assets/399eccb6-3036-4c3c-9c2a-8f63cbc0e096)

**Comment by Zidras** [comment]
> Can't you get gate health from combat log?

Sadly no. Only way to see gate hp afaik is in the tooltip (which is not implemented in dbm). I calculate gate timers based on damage done by vehicle and broadcasted by vehicle dbm (which most pvp players don't have)

**Comment by emv33** [comment]
How does MSBT see siege damage then? Is the event only sent to the player who damages the gate?

**Comment by Zidras** [comment]
> How does MSBT see siege damage then? Is the event only sent to the player who damages the gate?

Correct

**Comment by emv33** [comment]
![image](https://github.com/user-attachments/assets/bf8cf5cb-8493-4620-85f9-39b0d1b4229f)

**Comment by Zidras** [comment]
@emv33 , have you been able to get a Transcriptor log as requested?

**Comment by emv33** [comment]
Sorry, I don't intend to do that. Thanks for your time.
