### ISSUE TITLE
[BUG] Zul Aman settings are not saved

### ISSUE THREAD

**Issue by disis24** [Zidras/DBM-Warmane#217]
### Are you using the latest DBM version in a Warmane 3.3.5a realm (Icecrown, Lordaeron or Frostmourne)?

- [X] Yes

### DBM version

DBM 10.1.13 alpha 2024/09/03

### Current Behavior

Zul Aman settings are not saved when you log off.

### Expected Behavior

.

### Steps To Reproduce

.

### Transcriptor log

NA

**Comment by Zidras** [comment]
Bug confirmed, I'll fix the toc once I get home
