### ISSUE TITLE
AB score prediction goes to 1600. Game runs to 2000 max points

### ISSUE THREAD

**Issue by AiAnswer3213** [Zidras/DBM-Warmane#225]
### Are you using the latest DBM version in a Warmane 3.3.5a realm (Icecrown, Lordaeron or Frostmourne)?

Does onyxia count as 3.3.5? Idk

### DBM version

DBM 10.1.13 alpha (2024/09/03 09:29:29) / VPVEM: v14

### Current Behavior

![image](https://github.com/user-attachments/assets/c76df30b-5ec6-4261-bd04-1fccc50500ef)

on the onyxia realm the score is reported like this. Does this require some realm check for different behavior?

### Expected Behavior

-

### Steps To Reproduce

-

### Transcriptor log

-

**Comment by Zidras** [comment]
Oof, yes it does. And to be honest, supporting tbc pvp is not something I plan on working on.
I will however accept and review PR

**Comment by AiAnswer3213** [comment]
https://github.com/Zidras/DBM-Warmane/blob/bc1a188995e50c3a7ce0bdd1ccca0541d6cee44e/DBM-PvP/PvPGeneral.lua#L1035
https://github.com/Zidras/DBM-Warmane/blob/bc1a188995e50c3a7ce0bdd1ccca0541d6cee44e/DBM-PvP/PvPGeneral.lua#L818

`function mod:UpdateWinTimer(maxScore, allianceScore, hordeScore, allianceBases, hordeBases)`
`self:UpdateWinTimer(1600, tonumber(smatch((select(3, GetWorldStateUIInfo(subscribedMapID == 483 and 2 or 1)) or ""), "(%d+)/1600")) or 0, tonumber(smatch((select(3, GetWorldStateUIInfo(subscribedMapID == 483 and 3 or 2)) or ""), "(%d+)/1600")) or 0, allyBases, hordeBases)`

![image](https://github.com/user-attachments/assets/d81cc29f-61ee-4d69-8c32-512ebff8d705)
![image](https://github.com/user-attachments/assets/95d2fafa-4271-4266-a533-9ca7b0acecca)
![image](https://github.com/user-attachments/assets/b0390383-48c6-4479-a8b7-5c45643d5b19)

**Comment by AiAnswer3213** [comment]
https://github.com/Zidras/DBM-Warmane/pull/226
