### ISSUE TITLE
[BUG] Error when trying to import a profile

### ISSUE THREAD

**Issue by Zergei** [Zidras/DBM-Warmane#231]
### Are you using the latest DBM version in a Warmane 3.3.5a realm (Icecrown, Lordaeron or Frostmourne)?

- [X] Yes

### DBM version

 DBM 10.1.13 alpha (2024/09/03 09:29:29)

### Current Behavior

this error appeared when i tried to import a DBM profile (https://wago.io/-g1wZ48ya)

1x DBM-Core-10.1.13_alpha\DBM-Core.lua:5771: attempt to index local 'path' (a number value)
DBM-Core-10.1.13_alpha\DBM-Core.lua:5824: in function <DBM-Core\DBM-Core.lua:5820>
DBM-Core-10.1.13_alpha\DBM-Core.lua:5859: in function `PlaySoundFile'
DBM-Core-10.1.13_alpha\DBM-Core.lua:8190: in function `Show'
DBM-Core-10.1.13_alpha\DBM-Core.lua:6452: in function `DemoMode'
DBM-GUI-10.1.13_alpha\modules\options\general\Core_GUI.lua:58: in function <...\AddOns\DBM-GUI\modules\options\general\Core_GUI.lua:57>

Locals:
self = <table> {
 GetUnitIdFromCID = <function> @ DBM-Core\DBM-Core.lua:2332:
 MoveSpecialWarning = <function> @ DBM-Core\DBM-Core.lua:8960:
 StopLogging = <function> @ DBM-Core\DBM-Core.lua:5423:
 CheckVoicePackVersion = <function> @ DBM-Core\DBM-Core.lua:9740:
 GetNumGuildPlayersInZone = <function> @ DBM-Core\DBM-Core.lua:2091:
 MapSizes = <table> {}
 SortByTankAlpha = <function> @ DBM-Core\DBM-Core.lua:7235:
 GetUnitIdFromGUID = <function> @ DBM-Core\DBM-Core.lua:2168:
 CopyProfile = <function> @ DBM-Core\DBM-Core.lua:1643:
 CHAT_MSG_MONSTER_EMOTE = <function> @ DBM-Core\DBM-Core.lua:4601:
 shortTermEventsRegistered = 1
 CHAT_MSG_WHISPER = <function> @ DBM-Core\DBM-Core.lua:6255:
 SendPVPTimers = <function> @ DBM-Core\DBM-Core.lua:6082:
 DeleteProfile = <function> @ DBM-Core\DBM-Core.lua:1660:
 DungeonMusic = <table> {}
 ShowUpdateReminder = <function> @ DBM-Core\modules\UpdateReminder.lua:76:
 GetRaidRoster = <function> @ DBM-Core\DBM-Core.lua:2127:
 PLAYER_REGEN_DISABLED = <function> @ DBM-Core\DBM-Core.lua:4422:
 FireEvent = <function> @ DBM-Core\DBM-Core.lua:1551:
 CreateModLocalization = <function> @ DBM-Core\modules\objects\Localization.lua:90:
 IsEnabled = <function> @ DBM-Core\DBM-Core.lua:6371:
 GetMyPlayerInfo = <function> @ DBM-Core\DBM-Core.lua:2182:
 Capitalize = <function> @ DBM-Core\DBM-Core.lua:6480:
 ADDON_LOADED = <function> @ DBM-Core\DBM-Core.lua:1309:
 IconNumToTexture = <function> @ DBM-Core\DBM-Core.lua:6529:
 BossHealth = <table> {}
 BattleMusic = <table> {}
 ShowRaidIDRequestResults = <function> @ DBM-Core\DBM-Core.lua:4092:
 AddDefeatSound = <function> @ DBM-Core\modules\Sounds.lua:95:
 SortByMeleeRoster = <function> @ DBM-Core\DBM-Core.lua:7283:
 GetBossUnitId = <function> @ DBM-Core\DBM-Core.lua:2314:
 AddDefaultOptions = <function> @ DBM-Core\DBM-Core.lua:2396:
 UPDATE_MOUSEOVER_UNIT = <function> @ DBM-Core\DBM-Core.lua:3305:
 ZONE_CHANGED_NEW_AREA = <function> @ DBM-Core\DBM-Core.lua:3173:
 FilterRaidBossEmote = <function> @ DBM-Core\DBM-Core.lua:1134:
 RequestTimers = <function> @ DBM-Core\DBM-Core.lua:5975:
 UnregisterInCombatEvents = <function> @ DBM-Core\DBM-Core.lua:1017:
 lastAntiSpamFLASH = 17749.491
 SendTimers = <function> @ DBM-Core\DBM-Core.lua:6047:
 Debug = <function> @ DBM-Core\DBM-Core.lua:6536:
 FireCustomEvent = <function> @ DBM-Core\DBM-Core.lua:4699:
 UPDATE_BATTLEFIELD_STATUS = <function> @ DBM-Core\DBM-Core.lua:3008:
 Voices = <table> {}
 CheckNearby = <function> @ DBM-Core\DBM-Core.lua:2356:
 AddOns = <table> {}
 CHAT_MSG_MONSTER_YELL = <function> @ DBM-Core\DBM-Core.lua:4566:
 Options = <table> {}
 LFG_PROPOSAL_SHOW = <function> @ DBM-Core\DBM-Core.lua:2891:
 ReleaseRevision = 20240720000000
 GetModLocalization = <function> @ DBM-Core\modules\objects\Localization.lua:107:
 RegisterMapSize = <function> @ DBM-Core\DBM-Core.lua:6546:
 GetMusic = <function> @ DBM-Core\modules\Sounds.lua:183:
 RegisterShortTermEvents = <function> @ DBM-Core\DBM-Core.lua:1061:
 Music = <table> {}
 SortByGroup = <function> @ DBM-Core\DBM-Core.lua:7232:
 IsTrivial = <function> defi
  ---

### Expected Behavior

to import the profile without errors

### Steps To Reproduce

1. go to dbm
2. go to profile
3. import profile
4. paste code string

### Transcriptor log

NA

**Comment by Zidras** [comment]
Incompatible profile
