### ISSUE TITLE
LK val'kyr targets

### ISSUE THREAD

**Issue by Nispodzianka** [Zidras/DBM-Warmane#33]
**Describe the bug**
DBM does not always catch all people caught by val'kyr

**Video**
https://www.twitch.tv/videos/1127447314?t=1h28m3s
https://www.twitch.tv/videos/1118495913?t=1h43m32s

**Comment by Nispodzianka** [comment]
maybe it will be useful to solve the problem - not tested
https://wago.io/lOwLg1Wvd
> - On Warmane, if you already noticed yourself, some targets are not announced by DBM, this happens because for some reason when you check some person in Valkyr, sometimes it doesn't return true by calling UnitInVehicle.

**Comment by Zidras** [comment]
This is a server script issue, not DBM related. Feel free to report it on warmane's bugtracker

**Comment by Zidras** [comment]
> maybe it will be useful to solve the problem - not tested
> https://wago.io/lOwLg1Wvd
> 
> > * On Warmane, if you already noticed yourself, some targets are not announced by DBM, this happens because for some reason when you check some person in Valkyr, sometimes it doesn't return true by calling UnitInVehicle.

Already present on the second clip you posted, same issue
