### ISSUE TITLE
TOC-Champions

### ISSUE THREAD

**Issue by Nispodzianka** [Zidras/DBM-Warmane#38]
Message: Interface\AddOns\DBM-Core\DBM-Core.lua:8334: attempt to compare nil with number
Time: 09/04/21 16:20:00
Count: 1
Stack: [C]: ?
Interface\AddOns\DBM-Core\DBM-Core.lua:8334: in function `Play'
Interface\AddOns\DBM-Coliseum\Champions.lua:199: in function `?'
Interface\AddOns\DBM-Core\DBM-Core.lua:732: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:719>
(tail call): ?
Interface\AddOns\DBM-Core\DBM-Core.lua:732: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:719>

Locals:

**Comment by Zidras** [comment]
Fill the form. When does it happen, how to reproduce, etc

**Comment by Nispodzianka** [comment]
error occurs when opponents get BL which would explain error 199
specWarnHeroism: Play ("dispelboss")
I had this error at 25 and now at 10

**Comment by Zidras** [comment]
Paste me a screenshot of TOC champions boss dbm window

**Comment by Zidras** [comment]
And also a ss of your special warning filters

**Comment by Nispodzianka** [comment]
![WoWScrnShot_090421_170440](https://user-images.githubusercontent.com/87914582/132099085-e1af1ce8-672a-473a-aec5-7d7699420cde.jpg)

![WoWScrnShot_090421_162005](https://user-images.githubusercontent.com/87914582/132098950-24b4b7f5-e4e4-4b7c-abfe-8ade85f26acb.jpg)


these two screenshots below are not on the latest CORE
![WoWScrnShot_090321_193513](https://user-images.githubusercontent.com/87914582/132098979-572e68b4-c7b8-489c-804b-d34e883b1b6a.jpg)
![WoWScrnShot_090321_194513](https://user-images.githubusercontent.com/87914582/132098992-e82e3516-b41e-4ced-a566-94c2a8ca4247.jpg)

**Comment by Zidras** [comment]
> these two screenshots below are not on the latest CORE

Then I can't know if this error is even valid, nor which line did the error occur .
Update to latest version and reproduce the error. If it happens again, post it here and I will reopen

**Comment by Nispodzianka** [comment]
it looks like it's not just a TOC error, RS Zarithrian also error the same line CORE
![WoWScrnShot_090421_182109](https://user-images.githubusercontent.com/87914582/132101921-ffb36a3e-82ce-4b7d-a96a-67b17c542588.jpg)
Message: ...face\AddOns\DBM-ChamberOfAspects\Ruby\Zarithrian.lua:64: attempt to index global 'arg' (a nil value)
Time: 09/04/21 18:21:09
Count: 5
Stack: [C]: ?
...face\AddOns\DBM-ChamberOfAspects\Ruby\Zarithrian.lua:64: in function `?'
Interface\AddOns\DBM-Core\DBM-Core.lua:732: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:719>
(tail call): ?
Interface\AddOns\DBM-Core\DBM-Core.lua:732: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:719>

Locals:


Message: ...face\AddOns\DBM-ChamberOfAspects\Ruby\Zarithrian.lua:49: attempt to compare number with nil
Time: 09/04/21 18:21:39
Count: 1
Stack: [C]: ?
...face\AddOns\DBM-ChamberOfAspects\Ruby\Zarithrian.lua:49: in function `?'
Interface\AddOns\DBM-Core\DBM-Core.lua:732: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:719>
(tail call): ?
Interface\AddOns\DBM-Core\DBM-Core.lua:732: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:719>

Locals:

**Comment by Zidras** [comment]
> it looks like it's not just a TOC error, RS Zarithrian also error the same line CORE
> ![WoWScrnShot_090421_182109](https://user-images.githubusercontent.com/87914582/132101921-ffb36a3e-82ce-4b7d-a96a-67b17c542588.jpg)
> Message: ...face\AddOns\DBM-ChamberOfAspects\Ruby\Zarithrian.lua:64: attempt to index global 'arg' (a nil value)
> Time: 09/04/21 18:21:09
> Count: 5
> Stack: [C]: ?
> ...face\AddOns\DBM-ChamberOfAspects\Ruby\Zarithrian.lua:64: in function `?'
> Interface\AddOns\DBM-Core\DBM-Core.lua:732: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:719>
> (tail call): ?
> Interface\AddOns\DBM-Core\DBM-Core.lua:732: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:719>
> 
> Locals:
> 
> Message: ...face\AddOns\DBM-ChamberOfAspects\Ruby\Zarithrian.lua:49: attempt to compare number with nil
> Time: 09/04/21 18:21:39
> Count: 1
> Stack: [C]: ?
> ...face\AddOns\DBM-ChamberOfAspects\Ruby\Zarithrian.lua:49: in function `?'
> Interface\AddOns\DBM-Core\DBM-Core.lua:732: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:719>
> (tail call): ?
> Interface\AddOns\DBM-Core\DBM-Core.lua:732: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:719>
> 
> Locals:

Not the same. This is errors on your edits

**Comment by Nispodzianka** [comment]
today ToGC25
![WoWScrnShot_091021_200317](https://user-images.githubusercontent.com/87914582/132909453-2fe70c6a-167b-45b8-8261-4cb03e463b89.jpg)
![WoWScrnShot_091021_200031](https://user-images.githubusercontent.com/87914582/132909478-635b302d-6702-4952-a72c-69e3ce655c8c.jpg)
previously it was
		specWarnHeroism:Play("dispelboss")
now I had
		specWarnBloodlust:Play("dispelboss")
		specWarnHandofFreedom:Play("dispelboss")
on my shadow priest
