### ISSUE TITLE
Typo on Anub'arak Shadowstrike SPELL_CAST_START

### ISSUE THREAD

**Issue by Gescht** [Zidras/DBM-Warmane#49]
https://github.com/Zidras/DBM-Warmane/blob/6e2fa694688c9d5622c6577bb0b759ada81f2884/DBM-Coliseum/Anub'arak.lua#L204

Is "SpecWarn66134spell" intended?

**Comment by Gescht** [comment]
I'm used to DBM handling the option for warnings and specwarning automatically.
Maybe this is one of the new ways to handle this but 

```
elseif args.spellId == 66134 and self:AntiSpam(2, 1) then	-- Shadow Strike
	self:UnscheduleMethod("ShadowStrike")
	self:ShadowStrike() 
	specWarnShadowStrike:Show()
	warnShadowStrike:Show()
end
```

should do the same as

```
elseif args.spellId == 66134 and self:AntiSpam(2, 1) then	-- Shadow Strike
	self:UnscheduleMethod("ShadowStrike")
	self:ShadowStrike()
	if self.Options.SpecWarn66134spell then
		specWarnShadowStrike:Show()
	else
		warnShadowStrike:Show()
	end
end
```

**Comment by Zidras** [comment]
> https://github.com/Zidras/DBM-Warmane/blob/6e2fa694688c9d5622c6577bb0b759ada81f2884/DBM-Coliseum/Anub'arak.lua#L204
> 
> Is "SpecWarn66134spell" intended?

Yes. It's how the options are constructed, and can be used for checks.

> should do the same as

Not quite. This is a way to prevent the warning to show if the special warning is also enabled.
So, on your first code snippet, both the warning and the special warning would show simultaneously (if both were enabled).
On retail snippet:
- If only warning is enabled: only warning triggers;
- If only special warning is enabled: only specWarn triggers;
- If both are enabled: only specWarn triggers
