### ISSUE TITLE
LUA errors as of latest patch

### ISSUE THREAD

**Issue by jonomurphy** [Zidras/DBM-Warmane#51]
1x DBM-Core\DBM-Core.lua:6581: attempt to index local 'self' (a nil value)
DBM-Core\DBM-Core.lua:6526: in function GetRoleFlagValue'
DBM-Core\DBM-Core.lua:2648: in function LoadModOptions'
DBM-Core\DBM-Core.lua:3185: in function LoadMod'
DBM-Core\DBM-Core.lua:3149: in function LoadModsOnDemand'
DBM-Core\DBM-Core.lua:3112: in function `func'
DBM-Core\DBM-Core.lua:1351: in function <DBM-Core\DBM-Core.lua:1342>

If I reload once or twice, the errors disappear from buggrabber, but they will appear again, intermittently.

I've tried removing all of my old WTF files, but errors persist.

Have tried with just DBM on.

```

**Comment by Zidras** [comment]
What does this command print: /dbm ver

**Comment by jonomurphy** [comment]
Resolved [I had copied over the new files and there may have been an issue so I deleted and copied the new ones after]
