### ISSUE TITLE
/Pull 

### ISSUE THREAD

**Issue by Nnerrad** [Zidras/DBM-Warmane#63]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Video**
If applicable, add a video to help explain your problem.
https://streamable.com/3yhwfq 

**Additional context**

**Error Log**

```

```
I can't disable the audio countdown for / pull and I can't disable the visual Gold Numbers countdown for / pull either

**Comment by Zidras** [comment]
Thank you Nnerrad for your report. Just confirmed the bug, will fix it when I get the chance
