### ISSUE TITLE
[BUG] icc25 vali timers dont work

### ISSUE THREAD

**Issue by Nispodzianka** [Zidras/DBM-Warmane#68]
**Describe the bug**
on last ver DBM timers on Vali25 (norm and hc) dont work

**DBM Version**
`/dbm ver` 7.07 (7007)

**To Reproduce**
1. Go to icc on vali and start event

**Video**
Vali25 HC https://youtu.be/wV_Y8M-QJgQ
Vali25 Norm https://youtu.be/oVStlz_PyaY

**Comment by Zidras** [comment]
Run transcriptor with debuglevel 5 at pull and send me the log

**Comment by Zidras** [comment]
https://github.com/Zidras/DBM-Warmane/commit/7b6b1356478aeb79a048c6900a66ad22bd9852ef
Warmane bug. When they fix the yell, I will (maybe) revert if IEEU fails
