### ISSUE TITLE
DBM doest not support EPGP addon

### ISSUE THREAD

**Issue by koni3c** [Zidras/DBM-Warmane#70]
**Describe the bug**
In our guild we are using EPGP loot system. With the regular DBM, we were able to distribute EP points after each boss kill. With Zidras DBM, this feature stopped working. I have found in EPGP lua files that DBM is required for this feature.

**DBM Version**
7.07 DBM-Warmane by Zidras

**To Reproduce**
1. using EPGP 
2. Kill boss

**Expected behavior**
After each boss kill, EPGP popup offers EP points distribution

**Additional context**
As far as I understood, Zidras DBM is re-worked from DBM for later WoW patches, so my expectation is that some boss kill event is used by EPGP that probably changed by the time. It would be nice have this fixed even that bug is related to another addon :)
Thanks

**Comment by Zidras** [comment]
@koni3c has it ever worked on previous versions? If so, it would help to know which commit introduced this behavior

**Comment by koni3c** [comment]
@Zidras I don't know, I have just started using your DBM

**Comment by Zidras** [comment]
> @Zidras I don't know, I have just started using your DBM

Can you DM me on discord? I'd like you to test a potential fix.
