### ISSUE TITLE
[REQUEST] Normal/Heroic mode in DBM pull timer

### ISSUE THREAD

**Issue by oli356** [Zidras/DBM-Warmane#71]
**Is your feature request related to a problem? Please describe.**
I accidentally forget to change the difficulty to normal (or vice versa)

**Describe the solution you'd like**
In other releases of DBM when you do a /dbm pull xx it says normal or heroic. This would be nice to have here:
![image](https://user-images.githubusercontent.com/38960533/145628109-7e910c6e-6afb-4fc4-961f-0b1d11c5a520.png)

**Comment by Zidras** [comment]
Does this work? 
<img width="477" alt="image" src="https://user-images.githubusercontent.com/10605951/147822580-2df41472-8840-414b-8e88-3867f7667bc3.png">
<img width="385" alt="image" src="https://user-images.githubusercontent.com/10605951/147822593-f1f6fdf1-eed4-41d2-b04d-9c9cd8c43efc.png">

**Comment by oli356** [comment]
Yep @Zidras thats fine =)!
