### ISSUE TITLE
Nefarian error after the kill

### ISSUE THREAD

**Issue by JackieNL** [Zidras/DBM-Warmane#80]
1x DBM-StatusBarTimers\DBT.lua:884: attempt to call a nil value
DBM-BWL\Nefarian.lua:49: in function `func'
DBM-Core\DBM-Core.lua:1611: in function <DBM-Core\DBM-Core.lua:1602>

Locals:
self = <table> {
 CHAT_MSG_MONSTER_YELL = <function> @ DBM-BWL\Nefarian.lua:114:
 stats = <table> {}
 ignoreBestkill = false
 modId = "DBM-BWL"
 lastAntiSpamClassCall = 27288.05
 UNIT_DIED = <function> @ DBM-BWL\Nefarian.lua:92:
 revision = "7007"
 DefaultOptions = <table> {}
 iconRestore = <table> {}
 OnCombatStart = <function> @ DBM-BWL\Nefarian.lua:41:
 OnSync = <function> @ DBM-BWL\Nefarian.lua:145:
 UNIT_HEALTH = <function> @ DBM-BWL\Nefarian.lua:107:
 blockSyncs = true
 localization = <table> {}
 announces = <table> {}
 subTab = 1
 SPELL_CAST_START = <function> @ DBM-BWL\Nefarian.lua:71:
 specwarns = <table> {}
 OnCombatEnd = <function> @ DBM-BWL\Nefarian.lua:47:
 modelId = 11380
 lastKillTime = 27320.265
 zones = <table> {}
 combatInfo = <table> {}
 Options = <table> {}
 lastAntiSpamPhase = 27290.832
 addon = <table> {}
 inCombat = false
 timers = <table> {}
 categorySort = <table> {}
 registeredUnitEvents = <table> {}
 SyncThreshold = 8
 creatureId = 11583
 optionCategories = <table> {}
 SPELL_AURA_APPLIED = <function> @ DBM-BWL\Nefarian.lua:80:
 id = "Nefarian-Classic"
 vb = <table> {}
 inCombatOnlyEvents = <table> {}
}
wipe = nil
firstBossMod = <table> {
 timers = <table> {}
 categorySort = <table> {}
 stats = <table> {}
 modelId = 12435
 SyncThreshold = 8
 creatureId = 12435
 inCombatOnlyEvents = <table> {}
 CHAT_MSG_MONSTER_EMOTE = <function> @ DBM-BWL\Razorgore.lua:78:
 SPELL_AURA_APPLIED = <function> @ DBM-BWL\Razorgore.lua:71:
 modId = "DBM-BWL"
 iconRestore = <table> {}
 SPELL_CAST_START = <function> @ DBM-BWL\Razorgore.lua:49:
 combatInfo = <table> {}
 UNIT_DIED = <function> @ DBM-BWL\Razorgore.lua:84:
 zones = <table> {}
 revision = "7007"
 Options = <table> {}
 DefaultOptions = <table> {}
 id = "Razorgore"
 OnCombatStart = <function> @ DBM-BWL\Razorgore.lua:36:
 multiMobPullDetection = <table> {}
 OnSync = <function> @ DBM-BWL\Razorgore.lua:95:
 addon = <table> {}
 specwarns = <table> {}
 SPELL_CAST_SUCCESS = <function> @ DBM-BWL\Razorgore.lua:60:
 optionCategories = <table> {}
 localization = <table> {}
 announces = <table> {}
 vb = <table> {}
 subTab = 1
}

  ---

**Comment by Zidras** [comment]
Hello, thanks for your report. This problem will take a bit more time to fix, since its a global problem which runs deeper in the DBT bar iterator code.
This error specifically should not really happen to you again on BWL (would only trigger on the first time you went to BWL, because the mod didn't register the fastestClear timer yet in the saved variables (during nefarian kill), so on razorgore it didn't create a fastest clear bar timer). Nevertheless, I will keep this ticket open

**Comment by JackieNL** [comment]
Hey Zidras, i also got this error from Ragnaros? Like the same error?

**Comment by Zidras** [comment]
> Hey Zidras, i also got this error from Ragnaros? Like the same error?

Yes, it will happens on other bosses too, on the first clear. Everywhere that it has this code:
```
DBT:CancelBar(DBM_CORE_L.SPEED_CLEAR_TIMER_TEXT)
```

**Comment by JackieNL** [comment]
Alright :)
