### ISSUE TITLE
[REQUEST] Sent by in DBM Pulltimer can be deactivated or completely remove

### ISSUE THREAD

**Issue by NoM0Re** [Zidras/DBM-Warmane#94]
Hey Zidras

Is it Possible to do an Option to deactivate the Sent by in thw Pulltimer Raid Warning?
Its simply Useless and a reason to play the old Version of DBM for many.

**Describe the solution you'd like:**
Option to deactivate this or remove it just completly.

**Comment by Zidras** [comment]
I won't work on this since it is working like retail. Closing it, unless a working Pull Request is submitted.
