### ISSUE TITLE
[REQUEST]icc Valithria Abom counter 

### ISSUE THREAD

**Issue by Nispodzianka** [Zidras/DBM-Warmane#98]
on Vali please add the Abom counter as we have for Suppressers
there are tactics where a few initial Abom are killed and the 4th and later go into the shackle and such a counter would help

**Comment by Zidras** [comment]
Do you want to try PRing this feature?

**Comment by Zidras** [comment]
Closed with https://github.com/Zidras/DBM-Warmane/commit/b3193a3221af88242d664b2a8a396637c57a9ad8
